controller_manager:
  ros__parameters:
    update_rate: 30 

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    # English comment: Mandatory declaration of the aerial controller type
    aerial_joint_controller:
      type: position_controllers/JointGroupPositionController

# -----------------------------------------------------

# English comment: Specific configuration for the drone's vertical movement
aerial_joint_controller:
  ros__parameters:
    joints:
      - drone_to_terrestrial_joint
    interface_name: position

# -----------------------------------------------------

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.64
    wheel_radius: 0.1
    publish_rate: 50.0
    velocity_rolling_window_size: 10
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 0.5 
    linear.x.has_acceleration_limits: true
    linear.x.max_acceleration: 2.0 
    angular.z.max_acceleration: 3.0
    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 1.0 
    angular.z.has_acceleration_limits: true
    angular.z.max_acceleration: 2.0 
    publish_odom_tf: true
    odom_frame_id: odom
    base_frame_id: base_link
    use_stamped_vel: false